version: '3'
services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    ports:
      - "5432:5432"
  init_db:
    build: .
    command: bash -c "echo 'first npm install can be a bit long'; npm install; npm run migrate; npm run seed;"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://db:db@db:5432/db
    depends_on:
      - db
  web:
    build: .
    command: bash -c "npm run dev"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://db:db@db:5432/db
    ports:
      - "8080:8080"
      - "9229:9229"
    depends_on:
      - init_db
    restart: on-failure