version: '3'
services:
  web:
    build: .
    command: bash -c "npm run migrate; npm run test"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://db:db@db:5432/db
    depends_on:
      - db
    restart: on-failure