name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: docker-compose -f docker-compose.yml -f docker-compose-test.yml up --abort-on-container-exit;
    - run: docker ps -a
    - run: docker-compose run web ls /app/node_modules
    - run: docker-compose run init_db ls /app/node_modules
    - run: docker-compose run web npm run lint
    - run: docker-compose run init_db npm run lint
